"""Тесты конфигурации: дефолты, автогенерация ключа, идемпотентность, права."""

from __future__ import annotations

import os
import sys
from pathlib import Path

import pytest
from app.config import Settings, get_or_create_secret_key


def test_defaults_without_env() -> None:
    """Settings() без переменных окружения даёт профиль minimal."""
    settings = Settings()
    assert settings.app_name == "orqion"
    assert settings.profile == "minimal"
    assert settings.host == "127.0.0.1"
    assert settings.port == 8000
    assert settings.log_level == "INFO"
    assert settings.database_url == "sqlite:///./orqion.db"
    assert settings.vector_store == "sqlite-vec"
    assert settings.blob_store_path == "./data/blobs"
    assert settings.embeddings_model == "BAAI/bge-m3"
    assert settings.embeddings_backend == "local"
    assert settings.secret_key is None


def test_secret_key_autogenerated(tmp_path: Path) -> None:
    """Ключ генерируется при отсутствии и записывается в файл."""
    settings = Settings()
    data_dir = tmp_path / "data"
    key = get_or_create_secret_key(settings, data_dir)
    assert len(key) >= 32
    key_path = data_dir / ".secret_key"
    assert key_path.exists()
    assert key_path.read_text().strip() == key


def test_secret_key_idempotent(tmp_path: Path) -> None:
    """Повторный вызов возвращает тот же ключ из файла."""
    settings = Settings()
    data_dir = tmp_path / "data"
    key1 = get_or_create_secret_key(settings, data_dir)
    key2 = get_or_create_secret_key(settings, data_dir)
    assert key1 == key2


def test_secret_key_from_settings(tmp_path: Path) -> None:
    """ORQION_SECRET_KEY в окружении имеет приоритет над файлом."""
    os.environ["ORQION_SECRET_KEY"] = "explicit-key-from-env"
    try:
        settings = Settings()
        data_dir = tmp_path / "data"
        key = get_or_create_secret_key(settings, data_dir)
        assert key == "explicit-key-from-env"
        assert not (data_dir / ".secret_key").exists()
    finally:
        del os.environ["ORQION_SECRET_KEY"]


def test_secret_key_file_permissions(tmp_path: Path) -> None:
    """Файл .secret_key имеет права 0o600 на POSIX-системах."""
    if sys.platform == "win32":
        return  # NTFS не поддерживает Unix-права
    settings = Settings()
    data_dir = tmp_path / "data"
    get_or_create_secret_key(settings, data_dir)
    key_path = data_dir / ".secret_key"
    stat = key_path.stat()
    assert (stat.st_mode & 0o777) == 0o600


# TD-4: session_cookie_secure — дефолт зависимый от профиля


def test_session_cookie_secure_default_minimal(monkeypatch: pytest.MonkeyPatch) -> None:
    """Профиль minimal → session_cookie_secure=False (local, no TLS)."""
    monkeypatch.delenv("ORQION_SESSION_COOKIE_SECURE", raising=False)
    monkeypatch.delenv("ORQION_PROFILE", raising=False)
    settings = Settings()
    assert settings.profile == "minimal"
    assert settings.session_cookie_secure is False


def test_session_cookie_secure_standard_profile(monkeypatch: pytest.MonkeyPatch) -> None:
    """Профиль standard → session_cookie_secure=True (network, TLS)."""
    monkeypatch.delenv("ORQION_SESSION_COOKIE_SECURE", raising=False)
    monkeypatch.setenv("ORQION_PROFILE", "standard")
    settings = Settings()
    assert settings.profile == "standard"
    assert settings.session_cookie_secure is True


def test_session_cookie_secure_full_profile(monkeypatch: pytest.MonkeyPatch) -> None:
    """Профиль full → session_cookie_secure=True (network, TLS)."""
    monkeypatch.delenv("ORQION_SESSION_COOKIE_SECURE", raising=False)
    monkeypatch.setenv("ORQION_PROFILE", "full")
    settings = Settings()
    assert settings.profile == "full"
    assert settings.session_cookie_secure is True


def test_session_cookie_secure_explicit_override_true(monkeypatch: pytest.MonkeyPatch) -> None:
    """Явная ORQION_SESSION_COOKIE_SECURE=true побеждает дефолт профиля."""
    monkeypatch.setenv("ORQION_SESSION_COOKIE_SECURE", "true")
    monkeypatch.delenv("ORQION_PROFILE", raising=False)
    settings = Settings()
    assert settings.profile == "minimal"
    assert settings.session_cookie_secure is True


def test_session_cookie_secure_explicit_override_false(monkeypatch: pytest.MonkeyPatch) -> None:
    """Явная ORQION_SESSION_COOKIE_SECURE=false побеждает дефолт профиля."""
    monkeypatch.setenv("ORQION_SESSION_COOKIE_SECURE", "false")
    monkeypatch.setenv("ORQION_PROFILE", "standard")
    settings = Settings()
    assert settings.profile == "standard"
    assert settings.session_cookie_secure is False
