/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Analytics
         * @description Полный ответ аналитики: summary + by_day + by_model + by_user.
         */
        get: operations["get_analytics_api_analytics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat
         * @description Обработка чат-запроса. Стриминг или обычный режим.
         *
         *     Полный конвейер §7.1:
         *     1. resolve_policy(user)
         *     2. enforce (класс данных, модель, контекст, rate limits)
         *     3. маршрутизация → выбор модели
         *     4. выполнение запроса
         *     5. сохранение сообщений + usage_event + trace
         */
        post: operations["chat_api_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Conversations
         * @description Список диалогов пользователя. Только свои.
         */
        get: operations["list_conversations_api_conversations_get"];
        put?: never;
        /**
         * Create Conversation
         * @description Создание диалога. Заголовок — пустой до первого сообщения.
         */
        post: operations["create_conversation_api_conversations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Conversation
         * @description Чтение диалога с сообщениями. Только свои.
         */
        get: operations["get_conversation_api_conversations__conversation_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Conversation
         * @description Удаление диалога. Только свои.
         */
        delete: operations["delete_conversation_api_conversations__conversation_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Conversation
         * @description Переименование и архивация. Только свои.
         */
        patch: operations["update_conversation_api_conversations__conversation_id__patch"];
        trace?: never;
    };
    "/api/corpora/{corpus_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Documents Endpoint
         * @description Список документов корпуса.
         */
        get: operations["list_documents_endpoint_api_corpora__corpus_id__documents_get"];
        put?: never;
        /**
         * Upload Document Endpoint
         * @description Загрузка документа в корпус.
         *
         *     Оригинал сохраняется в BlobStore (ADR-7), затем создаётся Document(status=pending).
         *     Дубликат определяется по (corpus_id, sha256).
         */
        post: operations["upload_document_endpoint_api_corpora__corpus_id__documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Document Endpoint
         * @description Метаданные документа по ID (T-306).
         *
         *     Не возвращает blob_uri — это внутренний идентификатор хранения.
         */
        get: operations["get_document_endpoint_api_documents__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{document_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Document Content Endpoint
         * @description Потоковая отдача содержимого документа через BlobStore (T-306).
         *
         *     Оригинал читается через абстракцию BlobStore (ADR-7),
         *     не отдаёт blob_uri напрямую.
         */
        get: operations["get_document_content_endpoint_api_documents__document_id__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/corpora/{corpus_id}/eval-sets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Eval Sets
         * @description Список наборов оценки корпуса.
         */
        get: operations["list_eval_sets_api_corpora__corpus_id__eval_sets_get"];
        put?: never;
        /**
         * Create Eval Set
         * @description Создать набор оценки с элементами.
         */
        post: operations["create_eval_set_api_corpora__corpus_id__eval_sets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/eval-sets/{eval_set_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Eval Set
         * @description Получить набор с элементами.
         */
        get: operations["get_eval_set_api_eval_sets__eval_set_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Eval Set
         * @description Удалить набор оценки (каскадно удаляет элементы и прогоны).
         */
        delete: operations["delete_eval_set_api_eval_sets__eval_set_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/eval-sets/{eval_set_id}/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import To Eval Set
         * @description Импорт CodeSearchNet JSONL в существующий eval_set.
         *
         *     Файл парсится in-memory, не сохраняется на диск.
         */
        post: operations["import_to_eval_set_api_eval_sets__eval_set_id__import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/eval-sets/{eval_set_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Eval Runs
         * @description Список прогонов набора.
         */
        get: operations["list_eval_runs_api_eval_sets__eval_set_id__runs_get"];
        put?: never;
        /**
         * Create Eval Run
         * @description Запустить прогон оценки.
         */
        post: operations["create_eval_run_api_eval_sets__eval_set_id__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/eval-runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Eval Run
         * @description Получить прогон с метриками.
         */
        get: operations["get_eval_run_api_eval_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/eval-runs/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compare Eval Runs
         * @description Сравнить 2+ прогона по метрикам.
         *
         *     Прогоны сортируются по ts (по возрастанию) — «↑» всегда значит «стало лучше со временем».
         *     Сравнение запрещено для прогонов из разных eval_sets.
         */
        post: operations["compare_eval_runs_api_eval_runs_compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Available Models
         * @description Возвращает модели, доступные текущему пользователю.
         *
         *     Фильтрация:
         *     1. enabled=True у модели и провайдера
         *     2. policy.models для роли пользователя (resolve_policy)
         */
        get: operations["list_available_models_api_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Providers */
        get: operations["list_providers_api_providers_get"];
        put?: never;
        /** Create Provider */
        post: operations["create_provider_api_providers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers/{provider_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Provider */
        patch: operations["update_provider_api_providers__provider_id__patch"];
        trace?: never;
    };
    "/api/providers/{provider_id}/probe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Probe Provider Endpoint
         * @description Запускает probe провайдера: измеряет возможности, сверяет модели.
         *
         *     При deep=true — дополнительно измеряет фактический контекст (observed_context)
         *     для каждой available модели. Бинарный поиск, максимум 4 попытки на модель.
         *     Дорого: отправляет реальные промпты. Не входит в плановый ре-probe (T-112a).
         */
        post: operations["probe_provider_endpoint_api_providers__provider_id__probe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers/{provider_id}/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Model */
        post: operations["create_model_api_providers__provider_id__models_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers/models/{model_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Model */
        patch: operations["update_model_api_providers_models__model_id__patch"];
        trace?: never;
    };
    "/api/routing-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Routing Rules
         * @description Список правил маршрутизации. Доступ: manage_routing.
         */
        get: operations["list_routing_rules_api_routing_rules_get"];
        put?: never;
        /**
         * Create Routing Rule
         * @description Создание правила маршрутизации. Доступ: manage_routing.
         */
        post: operations["create_routing_rule_api_routing_rules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/routing-rules/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Routing Rule
         * @description Удаление правила маршрутизации. Доступ: manage_routing.
         *
         *     ADR-12: удаление seed-правила К2/К3 не влияет на фильтр data_class,
         *     т.к. _filter_data_class вызывается безусловно в коде.
         */
        delete: operations["delete_routing_rule_api_routing_rules__rule_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Routing Rule
         * @description Обновление правила маршрутизации. Доступ: manage_routing.
         */
        patch: operations["update_routing_rule_api_routing_rules__rule_id__patch"];
        trace?: never;
    };
    "/api/traces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Traces Endpoint
         * @description Список трассировок. Для admin — все в workspace, иначе — только свои.
         */
        get: operations["list_traces_endpoint_api_traces_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/traces/{trace_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Trace Endpoint
         * @description Полная трассировка со всеми span'ами.
         */
        get: operations["get_trace_endpoint_api_traces__trace_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalyticsResponse
         * @description Полный ответ аналитики.
         */
        AnalyticsResponse: {
            summary: components["schemas"]["AnalyticsSummary"];
            /** By Day */
            by_day: components["schemas"]["DailyBreakdown"][];
            /** By Model */
            by_model: components["schemas"]["ModelBreakdown"][];
            /** By User */
            by_user: components["schemas"]["UserBreakdown"][];
        };
        /**
         * AnalyticsSummary
         * @description Сводка за период.
         */
        AnalyticsSummary: {
            /** Total Requests */
            total_requests: number;
            /** Total Tokens In */
            total_tokens_in: number;
            /** Total Tokens Out */
            total_tokens_out: number;
            /** Total Cost */
            total_cost: number;
            /** Total Errors */
            total_errors: number;
            /** Avg Latency Ms */
            avg_latency_ms: number | null;
        };
        /** Body_import_to_eval_set_api_eval_sets__eval_set_id__import_post */
        Body_import_to_eval_set_api_eval_sets__eval_set_id__import_post: {
            /** File */
            file: string;
        };
        /** Body_upload_document_endpoint_api_corpora__corpus_id__documents_post */
        Body_upload_document_endpoint_api_corpora__corpus_id__documents_post: {
            /** File */
            file: string;
        };
        /** ChatMessage */
        ChatMessage: {
            /** Role */
            role: string;
            /** Content */
            content: string;
        };
        /** ChatRequest */
        ChatRequest: {
            /** Conversation Id */
            conversation_id?: string | null;
            /** Messages */
            messages: components["schemas"]["ChatMessage"][];
            /** Model Alias */
            model_alias?: string | null;
            /** Max Tokens */
            max_tokens?: number | null;
            /**
             * Temperature
             * @default 0.7
             */
            temperature: number;
            /**
             * Stream
             * @default true
             */
            stream: boolean;
            /** Corpus Data Class */
            corpus_data_class?: string | null;
            /** Corpus Name */
            corpus_name?: string | null;
            /** Task Type */
            task_type?: string | null;
        };
        /** ConversationCreate */
        ConversationCreate: {
            /** Title */
            title?: string | null;
        };
        /** ConversationDetailResponse */
        ConversationDetailResponse: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Archived */
            archived: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Message Count
             * @default 0
             */
            message_count: number;
            /**
             * Messages
             * @default []
             */
            messages: components["schemas"]["MessageResponse"][];
        };
        /** ConversationListResponse */
        ConversationListResponse: {
            /** Conversations */
            conversations: components["schemas"]["ConversationResponse"][];
            /** Total */
            total: number;
        };
        /** ConversationResponse */
        ConversationResponse: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Archived */
            archived: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Message Count
             * @default 0
             */
            message_count: number;
        };
        /** ConversationUpdate */
        ConversationUpdate: {
            /** Title */
            title?: string | null;
            /** Archived */
            archived?: boolean | null;
        };
        /**
         * DailyBreakdown
         * @description Разбивка по дням.
         */
        DailyBreakdown: {
            /** Date */
            date: string;
            /** Requests */
            requests: number;
            /** Tokens In */
            tokens_in: number;
            /** Tokens Out */
            tokens_out: number;
            /** Cost */
            cost: number;
            /** Errors */
            errors: number;
            /** Avg Latency Ms */
            avg_latency_ms: number | null;
        };
        /**
         * DocumentDetailResponse
         * @description Метаданные документа без внутреннего blob_uri (T-306).
         */
        DocumentDetailResponse: {
            /** Id */
            id: string;
            /** Corpus Id */
            corpus_id: string;
            /** Filename */
            filename: string;
            /** Mime */
            mime: string;
            /** Sha256 */
            sha256: string;
            /** Source Type */
            source_type: string;
            /** Status */
            status: string;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
        };
        /** DocumentListResponse */
        DocumentListResponse: {
            /** Documents */
            documents: components["schemas"]["DocumentResponse"][];
            /** Total */
            total: number;
        };
        /** DocumentResponse */
        DocumentResponse: {
            /** Id */
            id: string;
            /** Corpus Id */
            corpus_id: string;
            /** Filename */
            filename: string;
            /** Mime */
            mime: string;
            /** Sha256 */
            sha256: string;
            /** Blob Uri */
            blob_uri: string;
            /** Source Type */
            source_type: string;
            /** Status */
            status: string;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
        };
        /**
         * EvalCompareRequest
         * @description Запрос сравнения прогонов (POST /api/eval-runs/compare).
         */
        EvalCompareRequest: {
            /** Run Ids */
            run_ids: string[];
        };
        /**
         * EvalComparisonRead
         * @description Результат сравнения прогонов.
         */
        EvalComparisonRead: {
            /** Eval Set Id */
            eval_set_id: string;
            /** Runs */
            runs: components["schemas"]["RunMetadataRead"][];
            /** Deltas */
            deltas: components["schemas"]["MetricDeltaRead"][];
        };
        /**
         * EvalImportResponse
         * @description Результат импорта (POST /api/eval-sets/{id}/import).
         */
        EvalImportResponse: {
            /** Eval Set Id */
            eval_set_id: string;
            /** Total Items */
            total_items: number;
            /** Matched Items */
            matched_items: number;
        };
        /** EvalItemCreate */
        EvalItemCreate: {
            /** Question */
            question: string;
            /**
             * Expected Doc Ids
             * @default []
             */
            expected_doc_ids: string[];
            /** Expected Answer */
            expected_answer?: string | null;
        };
        /** EvalItemRead */
        EvalItemRead: {
            /** Id */
            id: string;
            /** Workspace Id */
            workspace_id: string;
            /** Eval Set Id */
            eval_set_id: string;
            /** Question */
            question: string;
            /** Expected Doc Ids */
            expected_doc_ids: string[];
            /** Expected Answer */
            expected_answer: string | null;
        };
        /**
         * EvalRunCreate
         * @description Запуск прогона (POST /api/eval-sets/{id}/runs).
         */
        EvalRunCreate: {
            /** Index Version Id */
            index_version_id: string;
            /** Steps */
            steps?: string[] | null;
        };
        /**
         * EvalRunListResponse
         * @description Список прогонов набора.
         */
        EvalRunListResponse: {
            /** Items */
            items: components["schemas"]["EvalRunRead"][];
        };
        /** EvalRunRead */
        EvalRunRead: {
            /** Id */
            id: string;
            /** Workspace Id */
            workspace_id: string;
            /** Eval Set Id */
            eval_set_id: string;
            /** Index Version Id */
            index_version_id: string | null;
            /** Pipeline */
            pipeline: {
                [key: string]: unknown;
            };
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            } | null;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
        };
        /**
         * EvalSetCreateWithItems
         * @description Создание набора с элементами (POST /api/corpora/{corpus_id}/eval-sets).
         */
        EvalSetCreateWithItems: {
            /** Name */
            name: string;
            /** Items */
            items: components["schemas"]["EvalItemCreate"][];
        };
        /**
         * EvalSetListResponse
         * @description Список наборов корпуса.
         */
        EvalSetListResponse: {
            /** Items */
            items: components["schemas"]["EvalSetRead"][];
        };
        /** EvalSetRead */
        EvalSetRead: {
            /** Id */
            id: string;
            /** Workspace Id */
            workspace_id: string;
            /** Corpus Id */
            corpus_id: string;
            /** Name */
            name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * EvalSetReadWithItems
         * @description Набор с элементами (GET /api/eval-sets/{id}).
         */
        EvalSetReadWithItems: {
            /** Id */
            id: string;
            /** Workspace Id */
            workspace_id: string;
            /** Corpus Id */
            corpus_id: string;
            /** Name */
            name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Items */
            items: components["schemas"]["EvalItemRead"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** LoginResponse */
        LoginResponse: {
            user: components["schemas"]["UserResponse"];
        };
        /** MessageResponse */
        MessageResponse: {
            /** Id */
            id: string;
            /** Role */
            role: string;
            /** Content */
            content: string;
            /** Model Id */
            model_id: string | null;
            /** Tokens In */
            tokens_in: number | null;
            /** Tokens Out */
            tokens_out: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Meta */
            meta: {
                [key: string]: unknown;
            };
        };
        /**
         * MetricDeltaRead
         * @description Дельта одной метрики между двумя прогонами.
         */
        MetricDeltaRead: {
            /** Metric Name */
            metric_name: string;
            /** Earlier Value */
            earlier_value: number;
            /** Later Value */
            later_value: number;
            /** Delta */
            delta: number;
            /** Direction */
            direction: string;
        };
        /**
         * ModelBreakdown
         * @description Разбивка по моделям.
         */
        ModelBreakdown: {
            /** Model Id */
            model_id: string | null;
            /** Model Alias */
            model_alias: string | null;
            /** Requests */
            requests: number;
            /** Tokens In */
            tokens_in: number;
            /** Tokens Out */
            tokens_out: number;
            /** Cost */
            cost: number;
            /** Errors */
            errors: number;
        };
        /** ModelCreate */
        ModelCreate: {
            /** Provider Id */
            provider_id: string;
            /** Alias */
            alias: string;
            /** Upstream Name */
            upstream_name: string;
            /**
             * Locality
             * @default local
             */
            locality: string;
            /** Max Input Tokens */
            max_input_tokens?: number | null;
            /** Max Output Tokens */
            max_output_tokens?: number | null;
            /**
             * Supports Reasoning
             * @default false
             */
            supports_reasoning: boolean;
            /** Cost In */
            cost_in?: number | null;
            /** Cost Out */
            cost_out?: number | null;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
        };
        /** ModelResponse */
        ModelResponse: {
            /** Id */
            id: string;
            /** Alias */
            alias: string;
            /** Upstream Name */
            upstream_name: string;
            /** Locality */
            locality: string;
            /** Max Input Tokens */
            max_input_tokens: number | null;
            /** Max Output Tokens */
            max_output_tokens: number | null;
            /** Supports Reasoning */
            supports_reasoning: boolean;
            /** Cost In */
            cost_in: number | null;
            /** Cost Out */
            cost_out: number | null;
            /** Enabled */
            enabled: boolean;
        };
        /** ModelUpdate */
        ModelUpdate: {
            /** Alias */
            alias?: string | null;
            /** Upstream Name */
            upstream_name?: string | null;
            /** Locality */
            locality?: string | null;
            /** Max Input Tokens */
            max_input_tokens?: number | null;
            /** Max Output Tokens */
            max_output_tokens?: number | null;
            /** Supports Reasoning */
            supports_reasoning?: boolean | null;
            /** Cost In */
            cost_in?: number | null;
            /** Cost Out */
            cost_out?: number | null;
            /** Enabled */
            enabled?: boolean | null;
        };
        /** ProviderCreate */
        ProviderCreate: {
            /** Kind */
            kind: string;
            /** Base Url */
            base_url: string;
            /** Api Key */
            api_key?: string | null;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
        };
        /** ProviderListResponse */
        ProviderListResponse: {
            /** Providers */
            providers: components["schemas"]["ProviderResponse"][];
        };
        /** ProviderResponse */
        ProviderResponse: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Base Url */
            base_url: string;
            /** Enabled */
            enabled: boolean;
            /** Capabilities */
            capabilities: {
                [key: string]: unknown;
            };
            /**
             * Models
             * @default []
             */
            models: components["schemas"]["ModelResponse"][];
        };
        /** ProviderUpdate */
        ProviderUpdate: {
            /** Base Url */
            base_url?: string | null;
            /** Api Key */
            api_key?: string | null;
            /** Enabled */
            enabled?: boolean | null;
        };
        /**
         * RoutingRuleCreate
         * @description Создание правила маршрутизации.
         */
        RoutingRuleCreate: {
            /** Order */
            order: number;
            /**
             * Is Default
             * @default false
             */
            is_default: boolean;
            /**
             * Is Terminal
             * @default false
             */
            is_terminal: boolean;
            /** When Corpus Class */
            when_corpus_class?: string[] | null;
            /** When Role */
            when_role?: string | null;
            /** When Task */
            when_task?: string | null;
            /** When Model Alias */
            when_model_alias?: string | null;
            /** To Models */
            to_models?: string[] | null;
            /** Allow Locality */
            allow_locality?: string[] | null;
            /** Fallback Models */
            fallback_models?: string[] | null;
            /**
             * Reason
             * @default
             */
            reason: string;
        };
        /**
         * RoutingRuleListResponse
         * @description Список правил маршрутизации.
         */
        RoutingRuleListResponse: {
            /** Rules */
            rules: components["schemas"]["RoutingRuleResponse"][];
            /** Total */
            total: number;
        };
        /**
         * RoutingRuleResponse
         * @description Ответ: правило маршрутизации.
         */
        RoutingRuleResponse: {
            /** Id */
            id: string;
            /** Order */
            order: number;
            /** Is Default */
            is_default: boolean;
            /** Is Terminal */
            is_terminal: boolean;
            /** When Corpus Class */
            when_corpus_class?: string[] | null;
            /** When Role */
            when_role?: string | null;
            /** When Task */
            when_task?: string | null;
            /** When Model Alias */
            when_model_alias?: string | null;
            /** To Models */
            to_models?: string[] | null;
            /** Allow Locality */
            allow_locality?: string[] | null;
            /** Fallback Models */
            fallback_models?: string[] | null;
            /**
             * Reason
             * @default
             */
            reason: string;
        };
        /**
         * RoutingRuleUpdate
         * @description Обновление правила маршрутизации. Все поля optional.
         */
        RoutingRuleUpdate: {
            /** Order */
            order?: number | null;
            /** Is Default */
            is_default?: boolean | null;
            /** Is Terminal */
            is_terminal?: boolean | null;
            /** When Corpus Class */
            when_corpus_class?: string[] | null;
            /** When Role */
            when_role?: string | null;
            /** When Task */
            when_task?: string | null;
            /** When Model Alias */
            when_model_alias?: string | null;
            /** To Models */
            to_models?: string[] | null;
            /** Allow Locality */
            allow_locality?: string[] | null;
            /** Fallback Models */
            fallback_models?: string[] | null;
            /** Reason */
            reason?: string | null;
        };
        /**
         * RunMetadataRead
         * @description Метаданные одного прогона в сравнении.
         */
        RunMetadataRead: {
            /** Run Id */
            run_id: string;
            /** Ts */
            ts: string;
            /** Index Version Id */
            index_version_id: string | null;
            /** Generate Model Alias */
            generate_model_alias: string;
            /** Rewrite Model Alias */
            rewrite_model_alias: string | null;
            /** Reranker Enabled */
            reranker_enabled: boolean;
            /** Steps */
            steps: string[];
        };
        /**
         * SpanResponse
         * @description Один шаг конвейера в трассировке.
         */
        SpanResponse: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Duration Ms */
            duration_ms: number | null;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
        };
        /**
         * TraceDetailResponse
         * @description Полная трассировка со всеми span'ами.
         */
        TraceDetailResponse: {
            /** Id */
            id: string;
            /** Conversation Id */
            conversation_id: string | null;
            /** Message Id */
            message_id: string | null;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Total Ms */
            total_ms: number | null;
            /** Status */
            status: string;
            /** Spans */
            spans: components["schemas"]["SpanResponse"][];
        };
        /**
         * TraceListResponse
         * @description Список трассировок.
         */
        TraceListResponse: {
            /** Traces */
            traces: components["schemas"]["TraceSummaryResponse"][];
            /** Total */
            total: number;
        };
        /**
         * TraceSummaryResponse
         * @description Краткая сводка трассировки (для списка).
         */
        TraceSummaryResponse: {
            /** Id */
            id: string;
            /** Conversation Id */
            conversation_id: string | null;
            /** Message Id */
            message_id: string | null;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Total Ms */
            total_ms: number | null;
            /** Status */
            status: string;
            /** Span Count */
            span_count: number;
        };
        /**
         * UserBreakdown
         * @description Разбивка по пользователям с текущей ролью.
         */
        UserBreakdown: {
            /** User Id */
            user_id: string | null;
            /** User Email */
            user_email: string | null;
            /** Role Name */
            role_name: string | null;
            /** Requests */
            requests: number;
            /** Tokens In */
            tokens_in: number;
            /** Tokens Out */
            tokens_out: number;
            /** Cost */
            cost: number;
            /** Errors */
            errors: number;
        };
        /** UserResponse */
        UserResponse: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Is Active */
            is_active: boolean;
            /** Capabilities */
            capabilities: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    get_analytics_api_analytics_get: {
        parameters: {
            query?: {
                /** @description Начало периода (ISO date) */
                start?: string | null;
                /** @description Конец периода (ISO date) */
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_api_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_conversations_api_conversations_get: {
        parameters: {
            query?: {
                /** @description Фильтр по архиву */
                archived?: boolean | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_conversation_api_conversations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_api_conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_conversation_api_conversations__conversation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_conversation_api_conversations__conversation_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_endpoint_api_corpora__corpus_id__documents_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                corpus_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_document_endpoint_api_corpora__corpus_id__documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                corpus_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_document_endpoint_api_corpora__corpus_id__documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_endpoint_api_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_content_endpoint_api_documents__document_id__content_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_eval_sets_api_corpora__corpus_id__eval_sets_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                corpus_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalSetListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_eval_set_api_corpora__corpus_id__eval_sets_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                corpus_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvalSetCreateWithItems"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalSetReadWithItems"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_eval_set_api_eval_sets__eval_set_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eval_set_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalSetReadWithItems"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_eval_set_api_eval_sets__eval_set_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eval_set_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_to_eval_set_api_eval_sets__eval_set_id__import_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eval_set_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_to_eval_set_api_eval_sets__eval_set_id__import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalImportResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_eval_runs_api_eval_sets__eval_set_id__runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eval_set_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRunListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_eval_run_api_eval_sets__eval_set_id__runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                eval_set_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvalRunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRunRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_eval_run_api_eval_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalRunRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_eval_runs_api_eval_runs_compare_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvalCompareRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalComparisonRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_available_models_api_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelResponse"][];
                };
            };
        };
    };
    list_providers_api_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderListResponse"];
                };
            };
        };
    };
    create_provider_api_providers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_provider_api_providers__provider_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    probe_provider_endpoint_api_providers__provider_id__probe_post: {
        parameters: {
            query?: {
                deep?: boolean;
            };
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_model_api_providers__provider_id__models_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_model_api_providers_models__model_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_routing_rules_api_routing_rules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutingRuleListResponse"];
                };
            };
        };
    };
    create_routing_rule_api_routing_rules_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoutingRuleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutingRuleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_routing_rule_api_routing_rules__rule_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_routing_rule_api_routing_rules__rule_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoutingRuleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutingRuleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_traces_endpoint_api_traces_get: {
        parameters: {
            query?: {
                conversation_id?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trace_endpoint_api_traces__trace_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trace_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
